/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;

/**
 *
 * @author schmidtu
 */
public class JDialog_Vorauswahl_PersonalAnwesenheit extends javax.swing.JDialog {

    /**
     * Creates new form JDialog_Vorauswahl_PersonalAnwesenheit
     */
    public JDialog_Vorauswahl_PersonalAnwesenheit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    Frame_PersonalAnwesenheit Frame_PersonalAnwesenheit;
    String SchichtNummerWithName;
    String Schicht;
    
    private void do_postBuild() {
        
        jComboBox_schicht.addItem("");
        jComboBox_schicht.addItem("Frühschicht");
        jComboBox_schicht.addItem("Nachtschicht");
        jComboBox_schicht.addItem("Spätschicht");
        
        jComboBox_schichtNummerWithName.addItem("");
        jComboBox_schichtNummerWithName.addItem("Schicht 1 (Ellenbruch)");
        jComboBox_schichtNummerWithName.addItem("Schicht 2 (Friedrich)");
        jComboBox_schichtNummerWithName.addItem("Schicht 3 (Hahn)");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_info = new javax.swing.JLabel();
        jComboBox_schichtNummerWithName = new javax.swing.JComboBox<>();
        jComboBox_schicht = new javax.swing.JComboBox<>();
        btn_accept = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lbl_info.setText("Wählen Sie bitte Ihre Schicht aus.");

        jComboBox_schichtNummerWithName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_schichtNummerWithNameActionPerformed(evt);
            }
        });

        jComboBox_schicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_schichtActionPerformed(evt);
            }
        });

        btn_accept.setText("Übernehmen");
        btn_accept.setEnabled(false);
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });

        btn_cancel.setText("Abbrechen");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_info)
                    .addComponent(jComboBox_schichtNummerWithName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_schicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_accept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_schichtNummerWithName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_schicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        do_postBuild();
    }//GEN-LAST:event_formWindowOpened

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        // TODO add your handling code here:     
        Schicht = jComboBox_schicht.getSelectedItem().toString();
        SchichtNummerWithName = jComboBox_schichtNummerWithName.getSelectedItem().toString();
        if (Frame_PersonalAnwesenheit != null && Frame_PersonalAnwesenheit.get_Instance() >= 1) {
            Frame_PersonalAnwesenheit.setAlwaysOnTop(true);
            Frame_PersonalAnwesenheit.setAlwaysOnTop(false);
        }
        else {
            Frame_PersonalAnwesenheit = new Frame_PersonalAnwesenheit(SchichtNummerWithName, Schicht);
            Frame_PersonalAnwesenheit.setTitle("Personal-Anwesenheit");
            Frame_PersonalAnwesenheit.setSize(Toolkit.getDefaultToolkit().getScreenSize().width - 345, Toolkit.getDefaultToolkit().getScreenSize().height - 30); // 595 x 842; 749, 1122
            Frame_PersonalAnwesenheit.setLocation(345, 0);
            Frame_PersonalAnwesenheit.setVisible(true);
        }
//        Schicht = jComboBox_schicht.getSelectedItem().toString();
//        SchichtNummerWithName = jComboBox_schichtNummerWithName.getSelectedItem().toString();
        this.dispose();
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void jComboBox_schichtNummerWithNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_schichtNummerWithNameActionPerformed
        // TODO add your handling code here:
        if (!jComboBox_schicht.getSelectedItem().equals("") && !jComboBox_schichtNummerWithName.getSelectedItem().equals("")) {
            btn_accept.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_schichtNummerWithNameActionPerformed

    private void jComboBox_schichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_schichtActionPerformed
        // TODO add your handling code here:
        if (!jComboBox_schicht.getSelectedItem().equals("") && !jComboBox_schichtNummerWithName.getSelectedItem().equals("")) {
            btn_accept.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_schichtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_Vorauswahl_PersonalAnwesenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_Vorauswahl_PersonalAnwesenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_Vorauswahl_PersonalAnwesenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Vorauswahl_PersonalAnwesenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialog_Vorauswahl_PersonalAnwesenheit dialog = new JDialog_Vorauswahl_PersonalAnwesenheit(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JComboBox<String> jComboBox_schicht;
    private javax.swing.JComboBox<String> jComboBox_schichtNummerWithName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_info;
    // End of variables declaration//GEN-END:variables
}
