/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DBTools.DB_ConnectionManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author schmidtu
 */
public class ArticleOverviewFrame extends javax.swing.JFrame {

    /**
     * Creates new form ArticleOverviewFrame
     */
    public ArticleOverviewFrame() {
        initComponents();
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(false);
        btn_cancel.setEnabled(false);
    }
    
    boolean myAnswerIfConnected;
    Connection myConnection;
    DefaultTableModel myTableModel;  
    TableRowSorter<DefaultTableModel> mySorter;
    DB_ConnectionManager MY_DBCM;
    String Old_Key;
    boolean Old_M1;
    boolean Old_M2;
    boolean Old_M3;
    boolean Old_M4;
    boolean Old_M5;    
    boolean Old_M6;
    boolean Old_M7;
    boolean Old_M8;
    boolean Old_M9;
    boolean Old_M10;
    boolean Old_M11;
    boolean Old_M12;
    String Old_Schicht;
    String Old_Bemerkungen;
    int OldSelection;
    String DataSet_Mode;
    
    private void do_preBuild() {
                
        getDBConnection();
        get_DBTableData();
        myTableModel = (DefaultTableModel) jTable_dbData.getModel();
        lbl_rowCount.setText(String.valueOf(myTableModel.getRowCount()));        
        createRowSorter(myTableModel);
    }
    
    private void createRowSorter(DefaultTableModel aModel) {
        mySorter = new TableRowSorter<>(aModel);
        jTable_dbData.setRowSorter(mySorter);
    }
    
    public void search() {
        String searchTerm = jTextField_searchValue.getText();
        mySorter.setRowFilter(RowFilter.regexFilter(searchTerm));
    }
    
    private void do_postBuild() {
                
        jTable_dbData.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            set_valuesIntoEditFields();
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_table = new javax.swing.JPanel();
        jScrollPane_table = new javax.swing.JScrollPane();
        jTable_dbData = new javax.swing.JTable();
        lbl_searchValue = new javax.swing.JLabel();
        jTextField_searchValue = new javax.swing.JTextField();
        btn_clearSearchValue = new javax.swing.JButton();
        lbl_rowCount = new javax.swing.JLabel();
        jPanel_editData = new javax.swing.JPanel();
        lbl_KPArtikelNummer = new javax.swing.JLabel();
        lbl_Schicht = new javax.swing.JLabel();
        jTextField_key = new javax.swing.JTextField();
        jTextField_Schicht = new javax.swing.JTextField();
        lbl_editData = new javax.swing.JLabel();
        jCheckBox_M1 = new javax.swing.JCheckBox();
        jCheckBox_M2 = new javax.swing.JCheckBox();
        jCheckBox_M3 = new javax.swing.JCheckBox();
        jCheckBox_M4 = new javax.swing.JCheckBox();
        jCheckBox_M5 = new javax.swing.JCheckBox();
        jCheckBox_M6 = new javax.swing.JCheckBox();
        jCheckBox_M7 = new javax.swing.JCheckBox();
        jCheckBox_M8 = new javax.swing.JCheckBox();
        jCheckBox_M9 = new javax.swing.JCheckBox();
        jCheckBox_M10 = new javax.swing.JCheckBox();
        jCheckBox_M11 = new javax.swing.JCheckBox();
        jCheckBox_M12 = new javax.swing.JCheckBox();
        jScrollPane_remarks = new javax.swing.JScrollPane();
        jTextArea_Bemerkungen = new javax.swing.JTextArea();
        btn_accept = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jPanel_footer = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable_dbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KP Artikel-Nr.", "Schicht", "M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "M11", "M12", "Bemerkungen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_dbData.setAutoscrolls(false);
        jScrollPane_table.setViewportView(jTable_dbData);
        if (jTable_dbData.getColumnModel().getColumnCount() > 0) {
            jTable_dbData.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable_dbData.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable_dbData.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(6).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(8).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(9).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(10).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(11).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(12).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(13).setPreferredWidth(40);
            jTable_dbData.getColumnModel().getColumn(14).setPreferredWidth(200);
        }

        lbl_searchValue.setText("Suchen:");

        jTextField_searchValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchValueKeyReleased(evt);
            }
        });

        btn_clearSearchValue.setText("x");
        btn_clearSearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSearchValueActionPerformed(evt);
            }
        });

        lbl_rowCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_rowCount.setPreferredSize(new java.awt.Dimension(36, 14));

        javax.swing.GroupLayout jPanel_tableLayout = new javax.swing.GroupLayout(jPanel_table);
        jPanel_table.setLayout(jPanel_tableLayout);
        jPanel_tableLayout.setHorizontalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addComponent(lbl_searchValue)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_tableLayout.createSequentialGroup()
                                .addComponent(jTextField_searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clearSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_rowCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane_table, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel_tableLayout.setVerticalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_searchValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_searchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rowCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane_table, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbl_KPArtikelNummer.setText("KP Artikel-Nr.");
        lbl_KPArtikelNummer.setEnabled(false);
        lbl_KPArtikelNummer.setPreferredSize(new java.awt.Dimension(100, 14));

        lbl_Schicht.setText("Schicht");
        lbl_Schicht.setEnabled(false);
        lbl_Schicht.setPreferredSize(new java.awt.Dimension(50, 14));

        jTextField_key.setEnabled(false);
        jTextField_key.setPreferredSize(new java.awt.Dimension(100, 20));

        jTextField_Schicht.setEnabled(false);
        jTextField_Schicht.setPreferredSize(new java.awt.Dimension(50, 20));

        lbl_editData.setText("Bearbeitung:");

        jCheckBox_M1.setText("<html>M 1 &nbsp &nbsp &nbsp STAL - Reinraum</html>");
        jCheckBox_M1.setEnabled(false);
        jCheckBox_M1.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M2.setText("<html>M 2 &nbsp &nbsp &nbsp STAL</html>");
        jCheckBox_M2.setEnabled(false);
        jCheckBox_M2.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M3.setText("<html>M 3 &nbsp &nbsp &nbsp Bandstahl</html>");
        jCheckBox_M3.setEnabled(false);
        jCheckBox_M3.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M4.setText("<html>M 4 &nbsp &nbsp &nbsp nicht verfügbar</html>");
        jCheckBox_M4.setEnabled(false);
        jCheckBox_M4.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M5.setText("<html>M 5 &nbsp &nbsp &nbsp Bandstahl mit Lochstanze, lange Kette</html>");
        jCheckBox_M5.setEnabled(false);
        jCheckBox_M5.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M6.setText("<html>M 6 &nbsp &nbsp &nbsp STAL und Bandstahl</html>");
        jCheckBox_M6.setEnabled(false);
        jCheckBox_M6.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M7.setText("<html>M 7 &nbsp &nbsp &nbsp Bandstahl</html>");
        jCheckBox_M7.setEnabled(false);
        jCheckBox_M7.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M8.setText("<html>M 8 &nbsp &nbsp &nbsp Bandstahl</html>");
        jCheckBox_M8.setEnabled(false);
        jCheckBox_M8.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M9.setText("<html>M 9 &nbsp &nbsp &nbsp Bandstahl - Reinraum</html>");
        jCheckBox_M9.setEnabled(false);
        jCheckBox_M9.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M10.setText("<html>M 10 &nbsp &nbsp Bandstahl</html>");
        jCheckBox_M10.setEnabled(false);
        jCheckBox_M10.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M11.setText("<html>M 11 &nbsp &nbsp besonders</html>");
        jCheckBox_M11.setEnabled(false);
        jCheckBox_M11.setPreferredSize(new java.awt.Dimension(300, 24));

        jCheckBox_M12.setText("<html>M 12 &nbsp &nbsp STAL</html>");
        jCheckBox_M12.setEnabled(false);
        jCheckBox_M12.setPreferredSize(new java.awt.Dimension(300, 24));

        jTextArea_Bemerkungen.setColumns(20);
        jTextArea_Bemerkungen.setRows(2);
        jTextArea_Bemerkungen.setBorder(javax.swing.BorderFactory.createTitledBorder("Bemerkungen"));
        jTextArea_Bemerkungen.setEnabled(false);
        jScrollPane_remarks.setViewportView(jTextArea_Bemerkungen);

        btn_accept.setText("Übernehmen");

        btn_cancel.setText("Abbrechen");

        btn_new.setText("Neu");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_edit.setText("Bearbeiten");

        btn_delete.setText("Löschen");

        javax.swing.GroupLayout jPanel_editDataLayout = new javax.swing.GroupLayout(jPanel_editData);
        jPanel_editData.setLayout(jPanel_editDataLayout);
        jPanel_editDataLayout.setHorizontalGroup(
            jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editDataLayout.createSequentialGroup()
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addComponent(lbl_KPArtikelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Schicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addComponent(jTextField_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Schicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_M12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_M5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addComponent(btn_accept)
                        .addGap(5, 5, 5)
                        .addComponent(btn_cancel))
                    .addComponent(jScrollPane_remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_editData)
                    .addGroup(jPanel_editDataLayout.createSequentialGroup()
                        .addComponent(btn_new)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel_editDataLayout.setVerticalGroup(
            jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editDataLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_editData)
                .addGap(18, 18, 18)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_KPArtikelNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Schicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Schicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_M1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_M2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_M12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addGap(13, 13, 13)
                .addGroup(jPanel_editDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_accept)
                    .addComponent(btn_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_close.setText("Schließen");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_footerLayout = new javax.swing.GroupLayout(jPanel_footer);
        jPanel_footer.setLayout(jPanel_footerLayout);
        jPanel_footerLayout.setHorizontalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_footerLayout.setVerticalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_editData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_editData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getDBConnection() { 
        MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
        if (!MY_DBCM.isConnnected()) {
            JOptionPane.showMessageDialog(null,
                    "Der Verbindungs-Aufbau zur Datenbank ist gescheitert. Bitte wenden Sie sich an den Entwickler.",
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE);
//            return;
        }        
    }
   
    private void get_DBTableData() {  
        
        try
        { 
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
//            String myTempSQL = "CREATE TABLE #tempSegment FROM DiafBDE.dbo.T_Segment";
            String mySQL = "SELECT * FROM DiafBDE.dbo.T_Artikel_Maschine_Schicht"; // ORDER BY T_Segment.pKey_KP"; // WHERE tma_abt='Technik'";
            ResultSet myResultSet = myStatement.executeQuery(mySQL);            
            int myColumns = myResultSet.getMetaData().getColumnCount();
            myTableModel = (DefaultTableModel) jTable_dbData.getModel();
            int allOldRows = myTableModel.getRowCount();
            if (allOldRows > 0) {
                myTableModel.setRowCount(0);
            }
            while (myResultSet.next()) {
                  
                String[] myValue = new String[myColumns];
                
                for (int i = 1; i <= myColumns; i++) {
                          
                    String myDataSet = myResultSet.getString(i);
                    myValue[i-1] = myDataSet;
                }  
                myTableModel.addRow(myValue); 
            }
            if (!myResultSet.next()) {
                
//                return;
            } 
        }
        catch (SQLException myException )
        {
            System.out.println(myException);
        }
        finally {
            try {
                set_textFieldsEmpty(); 
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
                System.out.println(myException);
            }
        } 
    }
    
    private void set_textFieldsEmpty() {
        jTextField_key.setText("");
        jTextField_Schicht.setText("");
        jTextArea_Bemerkungen.setText("");
        jCheckBox_M1.setSelected(false);
        jCheckBox_M2.setSelected(false);
        jCheckBox_M3.setSelected(false);
        jCheckBox_M4.setSelected(false);
        jCheckBox_M5.setSelected(false);
        jCheckBox_M6.setSelected(false);
        jCheckBox_M7.setSelected(false);
        jCheckBox_M8.setSelected(false);
        jCheckBox_M9.setSelected(false);
        jCheckBox_M10.setSelected(false);
        jCheckBox_M11.setSelected(false);
        jCheckBox_M12.setSelected(false);
    }
    
    private void set_valuesIntoEditFields() {
        if (!DataSet_Mode.equals("edit")) {
            OldSelection = jTable_dbData.getSelectedRow();
            if(OldSelection != -1) {
                String tempString;

                int myRow = jTable_dbData.convertRowIndexToModel(OldSelection);
                jTextField_key.setText(myTableModel.getValueAt(myRow, 0).toString().trim());
                
                jTextField_Schicht.setText(myTableModel.getValueAt(myRow, 1).toString().trim());

                tempString = myTableModel.getValueAt(myRow, 1).toString();
//                jFormattedTextField_Plattenstärke.setValue(Float.parseFloat(tempString));
                jTextArea_Bemerkungen.setText(myTableModel.getValueAt(myRow, 14).toString().trim());
                
                btn_edit.setEnabled(true);
                btn_delete.setEnabled(true); 
            }  
        }
    }
    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        do_preBuild();
        do_postBuild();
    }//GEN-LAST:event_formWindowOpened

    private void jTextField_searchValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchValueKeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jTextField_searchValueKeyReleased

    private void btn_clearSearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearSearchValueActionPerformed
        // TODO add your handling code here:
        jTextField_searchValue.setText("");
        search();
    }//GEN-LAST:event_btn_clearSearchValueActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        DataSet_Mode = "new";
        set_textFieldsEnabled(true);
        set_oldValues();
        set_textFieldsEmpty();
        jTextField_key.requestFocus();
        btn_new.setEnabled(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_accept.setEnabled(true);
        btn_cancel.setEnabled(true);
    }//GEN-LAST:event_btn_newActionPerformed

    private void set_textFieldsEnabled(boolean aBoolean) {
        
        for (int i=1; i < jPanel_editData.getComponentCount(); i++) {
            System.out.println(jPanel_editData.getComponentCount());
            if (jPanel_editData.getComponent(i).getName().startsWith("jCheckBox_") || jPanel_editData.getComponent(i).getName().startsWith("jText"))
            jPanel_editData.getComponent(i).setEnabled(true);
        }
        jTextField_key.setEnabled(aBoolean);
    }
    
    private void set_oldValues() {
        Old_Key = jTextField_key.getText().trim();
        Old_M1 = jCheckBox_M1.isSelected();
        Old_M2 = jCheckBox_M2.isSelected();
        Old_M3 = jCheckBox_M3.isSelected();
        Old_M4 = jCheckBox_M4.isSelected();
        Old_M5 = jCheckBox_M5.isSelected();    
        Old_M6 = jCheckBox_M6.isSelected();
        Old_M7 = jCheckBox_M7.isSelected();
        Old_M8 = jCheckBox_M8.isSelected();
        Old_M9 = jCheckBox_M9.isSelected();
        Old_M10 = jCheckBox_M10.isSelected();
        Old_M11 = jCheckBox_M11.isSelected();
        Old_M12 = jCheckBox_M12.isSelected();
        Old_Schicht = jTextField_Schicht.getText().trim();
        Old_Bemerkungen = jTextArea_Bemerkungen.getText().trim();
        
    }
    
    private void get_oldValues() {
        jTextField_key.setText(Old_Key);
        jCheckBox_M1.setSelected(Old_M1);
        jCheckBox_M2.setSelected(Old_M2);
        jCheckBox_M3.setSelected(Old_M3);
        jCheckBox_M4.setSelected(Old_M4);
        jCheckBox_M5.setSelected(Old_M5);  
        jCheckBox_M6.setSelected(Old_M6);
        jCheckBox_M7.setSelected(Old_M7);
        jCheckBox_M8.setSelected(Old_M8);
        jCheckBox_M9.setSelected(Old_M9);
        jCheckBox_M10.setSelected(Old_M10);
        jCheckBox_M11.setSelected(Old_M11);
        jCheckBox_M12.setSelected(Old_M12);
        jTextField_Schicht.setText(Old_Schicht);
        jTextArea_Bemerkungen.setText(Old_Bemerkungen);
        
    }
    
    private void do_insertDataSet_intoDB() {        
        try
        {
//            System.out.println(((Number) jFormattedTextField_value2.getValue()).floatValue());
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {    
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("INSERT INTO DiafBDE.dbo.T_Artikel_Maschine_Schicht (pKey_KP, Plattenstärke)" 
                    + "VALUES ('" + jCheckBox_M1.isSelected() + "', '" 
                    + jCheckBox_M2.isSelected() +"')");  
//                    + ((Number) jFormattedTextField_Segmenthöhe.getValue()).floatValue() +"')");               
            } 
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }
    
    private void do_updateDataSet_inDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {   
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("UPDATE DiafBDE.dbo.T_Artikel_Maschine_Schicht SET Plattenstärke = '" + jCheckBox_M1.isSelected() +
                    "' WHERE pKey_KP = '" + jTextField_key.getText() + "'");             
            } 
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }
    
    private void do_deleteDataSet_inDB() {        
        try
        {
            MY_DBCM.setConnection_CLOSED("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "DISCONNECT");
            MY_DBCM = new DB_ConnectionManager("jdbc:sqlserver://HV-ABAS-SQL;databaseName=DiafBDE;integratedSecurity=true", "CONNECT");
            if (MY_DBCM.isConnnected()) 
            {   
            myConnection = MY_DBCM.getConnection();
            Statement myStatement = myConnection.createStatement();
            myStatement.executeUpdate("DELETE FROM DiafBDE.dbo.T_Artikel_Maschine_Schicht WHERE pKey_KP = '" + jTextField_key.getText().trim() + "'");             
            }   
        }
        catch (/*ClassNotFoundException |*/ SQLException myException )
        {
        }
        finally {
            try {
                if (myConnection != null && !myConnection.isClosed()) {
                    myConnection.close();
                }
            } catch (SQLException myException) {
            }
        }         
    }
    
    private boolean test_isDataSetInDB(String aString) {
        boolean myAnswer = false;
        for (int myRow = 0; myRow < jTable_dbData.getRowCount(); ++myRow ) {
            if (myTableModel.getValueAt(myRow, 0).toString().trim().equals(aString))
                myAnswer = true;           
        }
        return myAnswer;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticleOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticleOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticleOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticleOverviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ArticleOverviewFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clearSearchValue;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_new;
    private javax.swing.JCheckBox jCheckBox_M1;
    private javax.swing.JCheckBox jCheckBox_M10;
    private javax.swing.JCheckBox jCheckBox_M11;
    private javax.swing.JCheckBox jCheckBox_M12;
    private javax.swing.JCheckBox jCheckBox_M2;
    private javax.swing.JCheckBox jCheckBox_M3;
    private javax.swing.JCheckBox jCheckBox_M4;
    private javax.swing.JCheckBox jCheckBox_M5;
    private javax.swing.JCheckBox jCheckBox_M6;
    private javax.swing.JCheckBox jCheckBox_M7;
    private javax.swing.JCheckBox jCheckBox_M8;
    private javax.swing.JCheckBox jCheckBox_M9;
    private javax.swing.JPanel jPanel_editData;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JPanel jPanel_table;
    private javax.swing.JScrollPane jScrollPane_remarks;
    private javax.swing.JScrollPane jScrollPane_table;
    private javax.swing.JTable jTable_dbData;
    private javax.swing.JTextArea jTextArea_Bemerkungen;
    private javax.swing.JTextField jTextField_Schicht;
    private javax.swing.JTextField jTextField_key;
    private javax.swing.JTextField jTextField_searchValue;
    private javax.swing.JLabel lbl_KPArtikelNummer;
    private javax.swing.JLabel lbl_Schicht;
    private javax.swing.JLabel lbl_editData;
    private javax.swing.JLabel lbl_rowCount;
    private javax.swing.JLabel lbl_searchValue;
    // End of variables declaration//GEN-END:variables
}
