/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Toolkit;
/**
 *
 * @author schmidtu
 */
public class AV_MM_MainFrame extends javax.swing.JFrame {

//    public String [] stringOfFiles; 
    /**
     * Creates new form AV_MM_MainFrame
     */
    public AV_MM_MainFrame() {
        initComponents();
    }
    ConverterFrame converterFrame;
    ArticleOverviewFrame articleOverviewFrame;
    String pathExcelGreenMaps = "U:\\Ablage\\kunsttech\\Arbeitsvorbereitung\\04_Stammdaten\\";        
    String pathPDFVerpackungsvorschrift = "W:\\diaf003bilder\\Verpackungsvorschrift2\\";       
    String pathPDFPruefprotokoll = "W:\\diaf003bilder\\Prüfprotokoll\\";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_base = new javax.swing.JPanel();
        jPanel_modules = new javax.swing.JPanel();
        panel_modulConverter = new javax.swing.JPanel();
        lbl_info_ModulConverter = new javax.swing.JLabel();
        btn_openModul_Verpackungsvorschrift = new javax.swing.JButton();
        btn_openModul_Pruefprotokoll = new javax.swing.JButton();
        jPanel_modul_artikelMaschineSchicht = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_openModul_Uebersicht_ArtikelMaschineSchicht = new javax.swing.JButton();
        jPanel_footer = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        ToolBar_MainFrame = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setBounds(new java.awt.Rectangle(20, 20, 0, 0));

        jPanel_base.setBackground(new java.awt.Color(153, 255, 255));

        jPanel_modules.setOpaque(false);

        panel_modulConverter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_modulConverter.setOpaque(false);
        panel_modulConverter.setPreferredSize(new java.awt.Dimension(300, 113));

        lbl_info_ModulConverter.setText("Modul: Konverter Excel -> PDF");

        btn_openModul_Verpackungsvorschrift.setText("Verpackungsvorschrift");
        btn_openModul_Verpackungsvorschrift.setToolTipText("Öffnet das Modul zum Umwandeln von Excel-Dateien -> PDF.");
        btn_openModul_Verpackungsvorschrift.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_openModul_Verpackungsvorschrift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openModul_VerpackungsvorschriftActionPerformed(evt);
            }
        });

        btn_openModul_Pruefprotokoll.setText("Prüfprotokoll");
        btn_openModul_Pruefprotokoll.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_openModul_Pruefprotokoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openModul_PruefprotokollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_modulConverterLayout = new javax.swing.GroupLayout(panel_modulConverter);
        panel_modulConverter.setLayout(panel_modulConverterLayout);
        panel_modulConverterLayout.setHorizontalGroup(
            panel_modulConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modulConverterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modulConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modulConverterLayout.createSequentialGroup()
                        .addComponent(lbl_info_ModulConverter)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_openModul_Pruefprotokoll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(btn_openModul_Verpackungsvorschrift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_modulConverterLayout.setVerticalGroup(
            panel_modulConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modulConverterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_info_ModulConverter)
                .addGap(18, 18, 18)
                .addComponent(btn_openModul_Verpackungsvorschrift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_openModul_Pruefprotokoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_modulConverterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_openModul_Pruefprotokoll, btn_openModul_Verpackungsvorschrift});

        jPanel_modul_artikelMaschineSchicht.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_modul_artikelMaschineSchicht.setOpaque(false);
        jPanel_modul_artikelMaschineSchicht.setPreferredSize(new java.awt.Dimension(300, 79));

        jLabel1.setText("Modul: Übersicht Artikel-Maschine-Schicht");

        btn_openModul_Uebersicht_ArtikelMaschineSchicht.setText("Übersicht: Artikel-Maschine-Schicht");
        btn_openModul_Uebersicht_ArtikelMaschineSchicht.setPreferredSize(new java.awt.Dimension(200, 36));
        btn_openModul_Uebersicht_ArtikelMaschineSchicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openModul_Uebersicht_ArtikelMaschineSchichtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_modul_artikelMaschineSchichtLayout = new javax.swing.GroupLayout(jPanel_modul_artikelMaschineSchicht);
        jPanel_modul_artikelMaschineSchicht.setLayout(jPanel_modul_artikelMaschineSchichtLayout);
        jPanel_modul_artikelMaschineSchichtLayout.setHorizontalGroup(
            jPanel_modul_artikelMaschineSchichtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modul_artikelMaschineSchichtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_modul_artikelMaschineSchichtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_modul_artikelMaschineSchichtLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_openModul_Uebersicht_ArtikelMaschineSchicht, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_modul_artikelMaschineSchichtLayout.setVerticalGroup(
            jPanel_modul_artikelMaschineSchichtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modul_artikelMaschineSchichtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_openModul_Uebersicht_ArtikelMaschineSchicht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_modulesLayout = new javax.swing.GroupLayout(jPanel_modules);
        jPanel_modules.setLayout(jPanel_modulesLayout);
        jPanel_modulesLayout.setHorizontalGroup(
            jPanel_modulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_modul_artikelMaschineSchicht, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_modulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_modulesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_modulConverter, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_modulesLayout.setVerticalGroup(
            jPanel_modulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modulesLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jPanel_modul_artikelMaschineSchicht, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jPanel_modulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_modulesLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(panel_modulConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );

        jPanel_footer.setOpaque(false);

        btn_close.setBackground(new java.awt.Color(255, 51, 51));
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("Programm beenden");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_footerLayout = new javax.swing.GroupLayout(jPanel_footer);
        jPanel_footer.setLayout(jPanel_footerLayout);
        jPanel_footerLayout.setHorizontalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_footerLayout.setVerticalGroup(
            jPanel_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_footerLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ToolBar_MainFrame.setRollover(true);
        ToolBar_MainFrame.setPreferredSize(new java.awt.Dimension(13, 25));

        javax.swing.GroupLayout jPanel_baseLayout = new javax.swing.GroupLayout(jPanel_base);
        jPanel_base.setLayout(jPanel_baseLayout);
        jPanel_baseLayout.setHorizontalGroup(
            jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar_MainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_modules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_baseLayout.setVerticalGroup(
            jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_baseLayout.createSequentialGroup()
                .addComponent(ToolBar_MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addComponent(jPanel_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_baseLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jPanel_modules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void btn_openModul_VerpackungsvorschriftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openModul_VerpackungsvorschriftActionPerformed
        // TODO add your handling code here:    
            converterFrame = new ConverterFrame(pathExcelGreenMaps, pathPDFVerpackungsvorschrift, "VP", "av"); //Grüne Mappe -> "Verpackungsvorschrift"
            converterFrame.setTitle("Datei-Konverter");
            converterFrame.setSize(927, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            converterFrame.setLocation(345, 0);
            converterFrame.setVisible(true);        
    }//GEN-LAST:event_btn_openModul_VerpackungsvorschriftActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_openModul_PruefprotokollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openModul_PruefprotokollActionPerformed
        // TODO add your handling code here: 
            converterFrame = new ConverterFrame(pathExcelGreenMaps, pathPDFPruefprotokoll, "Prüf neu", "av"); //Grüne Mappe -> "Verpackungsvorschrift"
            converterFrame.setTitle("Datei-Konverter");
            converterFrame.setSize(927, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            converterFrame.setLocation(345, 0);
            converterFrame.setVisible(true);           
    }//GEN-LAST:event_btn_openModul_PruefprotokollActionPerformed

    private void btn_openModul_Uebersicht_ArtikelMaschineSchichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openModul_Uebersicht_ArtikelMaschineSchichtActionPerformed
        // TODO add your handling code here:    
        if (articleOverviewFrame != null && articleOverviewFrame.getInstance() >= 1) {
            articleOverviewFrame.setAlwaysOnTop(true);
            articleOverviewFrame.setAlwaysOnTop(false);
        }
        else {
            articleOverviewFrame = new ArticleOverviewFrame();
            articleOverviewFrame.setTitle("Übersicht: Artikel-Maschine-Schicht");
            articleOverviewFrame.setSize(1265, Toolkit.getDefaultToolkit().getScreenSize().height - 30);
            articleOverviewFrame.setLocation(345, 0);
            articleOverviewFrame.setVisible(true);
        }
    }//GEN-LAST:event_btn_openModul_Uebersicht_ArtikelMaschineSchichtActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AV_MM_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AV_MM_MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar ToolBar_MainFrame;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_openModul_Pruefprotokoll;
    private javax.swing.JButton btn_openModul_Uebersicht_ArtikelMaschineSchicht;
    private javax.swing.JButton btn_openModul_Verpackungsvorschrift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_base;
    private javax.swing.JPanel jPanel_footer;
    private javax.swing.JPanel jPanel_modul_artikelMaschineSchicht;
    private javax.swing.JPanel jPanel_modules;
    private javax.swing.JLabel lbl_info_ModulConverter;
    private javax.swing.JPanel panel_modulConverter;
    // End of variables declaration//GEN-END:variables
}
