/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
//import org.apache.poi.hssf.usermodel.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.commons.collections4.*;
import org.apache.xmlbeans.*;
import org.apache.xmlbeans.impl.common.*;

/**
 *
 * @author schmidtu
 */
public class ConverterFrame extends javax.swing.JFrame {       
  
    /** Creates new form ConverterFrame
     * @param aSourcePath
     * @param aDestinationPath */
    public ConverterFrame(String aSourcePath, String aDestinationPath) {
        initComponents(); 
        
        this.do_fillTableWithSourceFiles(aSourcePath);
        this.do_fillTableWithDestinationFiles(aDestinationPath); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_close = new javax.swing.JButton();
        btn_convertToPDF = new javax.swing.JButton();
        lbl_listCount_source = new javax.swing.JLabel();
        lbl_listCount_destination = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_sourceFiles = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_destinationFiles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 0, 0));

        jToolBar1.setRollover(true);

        btn_close.setText("Schließen");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_convertToPDF.setText("Excel -> PDF");
        btn_convertToPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertToPDFActionPerformed(evt);
            }
        });

        lbl_listCount_source.setText("123");

        lbl_listCount_destination.setText("123");

        table_sourceFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Änderungsdatum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_sourceFiles);

        table_destinationFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Änderungsdatum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table_destinationFiles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_close)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_listCount_source))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_convertToPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_listCount_destination))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_listCount_destination)
                    .addComponent(lbl_listCount_source))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addComponent(btn_convertToPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(721, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void do_fillTableWithSourceFiles(String aSourcePath)
    {        
        SimpleDateFormat myFormat = new SimpleDateFormat("dd.MM.yyyy   HH:mm:ss");
        DefaultTableModel myTableModel = (DefaultTableModel) table_sourceFiles.getModel();
        Date myModifiedDate;
        File f = new File(aSourcePath);
        File [] myFileList;
        myFileList = f.listFiles();
        int myCountOfFiles = myFileList.length;
        for (int currentIndex = 0; currentIndex < myCountOfFiles; currentIndex++)
        {   
            if (myFileList[currentIndex].getName().startsWith("kp") && (myFileList[currentIndex].getName().endsWith(".xls") || (myFileList[currentIndex].getName().endsWith(".xlsx"))) && !myFileList[currentIndex].getName().contains("vk"))
            { 
                myModifiedDate = new Date(myFileList[currentIndex].lastModified());
                myTableModel.addRow(new Object[] {myFileList[currentIndex].getName(), myFormat.format(myModifiedDate)});
            }
        }  
        TableRowSorter<TableModel> mySorter = new TableRowSorter<>(table_sourceFiles.getModel());
        table_sourceFiles.setRowSorter(mySorter);
        mySorter.setModel(myTableModel);
        lbl_listCount_source.setText(String.valueOf(myTableModel.getRowCount()));
        if (myTableModel.getRowCount() > 0)
        {
            btn_convertToPDF.setEnabled(true);
        }       
    }
    
    private void do_fillTableWithDestinationFiles(String aDestinationPath)
    {  
        DefaultTableModel tableModel;
        File f = new File(aDestinationPath);
        File [] myFileList;
        myFileList = f.listFiles();
        int myCountOfFiles = myFileList.length;
        for (int currentIndex = 0; currentIndex < myCountOfFiles; currentIndex++)
        { 
            tableModel = (DefaultTableModel) table_destinationFiles.getModel();
            tableModel.addRow(new Object[] {myFileList[currentIndex].getName(), myFileList[currentIndex].lastModified()});            
        }
    }
    
    private void btn_convertToPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertToPDFActionPerformed
        // TODO add your handling code here:
        //        System.out.println(list_sourceFiles.getSelectedValue());
        String myExcelPath = "U:\\Ablage\\kunsttech\\Arbeitsvorbereitung\\04_Stammdaten\\";
        String myPDFPath = "W:\\diaf003bilder\\Verpackungsvorschrift2\\";
        Object myRowObject;
        Workbook workbook;                  
        FileOutputStream myOutputStream;
        DefaultTableModel tableModel = (DefaultTableModel) table_sourceFiles.getModel();
        int myRowCount = table_sourceFiles.getRowCount();
        System.out.println("Beginn: " + new Date());
        for (int myRowIndex = 0; myRowIndex < myRowCount; myRowIndex++)
        {
            myRowObject = tableModel.getValueAt(myRowIndex, 0);
            String myRowValue = myRowObject.toString();
            if (myRowValue.endsWith(".xls") || myRowValue.endsWith(".xlsx"))
            {
                InputStream myInputStream = null;
                try
                {           
                    myInputStream = new FileInputStream(myExcelPath + myRowValue);
                    
                    workbook = WorkbookFactory.create(myInputStream);
                    int mySheetCount = workbook.getNumberOfSheets();
                    for (int sheetIndex = mySheetCount -1; sheetIndex >= 0; --sheetIndex)
                    {
                        if (!workbook.getSheetName(sheetIndex).toUpperCase().startsWith("VP"))
                        {
                            workbook.removeSheetAt(sheetIndex);
                        }
                          
//                        myOutputStream = null;
//                        myDataSet.substring(0, myDataSet.indexOf("."));
                    }
                    myOutputStream = new FileOutputStream(myPDFPath + myRowValue.substring(0, myRowValue.indexOf("."))+ ".pdf"); 
                    workbook.write(myOutputStream);
                }
                catch (FileNotFoundException ex) 
                {
                    Logger.getLogger(ConverterFrame.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("file not found");
                }
                catch (IOException | InvalidFormatException | EncryptedDocumentException ex) 
                {
                    Logger.getLogger(ConverterFrame.class.getName()).log(Level.SEVERE, null, ex);
                    System.out.println("IO, invalid format or encrypted document");                    
                }
                finally
                {
                    try {
                        if (myInputStream != null)
                        {
                            myInputStream.close();
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(ConverterFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } 
        }
        
        System.out.println("Ende: " + new Date());
    }//GEN-LAST:event_btn_convertToPDFActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            String temp = "eins";
            String temp2  = "zwei";
            new ConverterFrame(temp, temp2).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_convertToPDF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_listCount_destination;
    private javax.swing.JLabel lbl_listCount_source;
    private javax.swing.JTable table_destinationFiles;
    private javax.swing.JTable table_sourceFiles;
    // End of variables declaration//GEN-END:variables
   
 }
