/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.DefaultListModel;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.hssf.usermodel.*;
import org.apache.poi.ss.usermodel.*;


/**
 *
 * @author schmidtu
 */
public class ConverterFrame extends javax.swing.JFrame {       
  
    /** Creates new form ConverterFrame
     * @param anArraySourceFiles
     * @param anArrayDestinationFiles */
    public ConverterFrame(String [] anArraySourceFiles, String [] anArrayDestinationFiles) {
        initComponents(); 
        
        list_sourceFiles.setModel(new DefaultListModel());
        DefaultListModel listModelSource = (DefaultListModel)list_sourceFiles.getModel();
        for (int indexSource = 0; indexSource < anArraySourceFiles.length; indexSource++)
        {            
            listModelSource.add(indexSource, anArraySourceFiles[indexSource]);
            lbl_listCount_source.setText(String.valueOf(listModelSource.getSize()));
        }         
        list_destinationFiles.setModel(new DefaultListModel());
        DefaultListModel listModelDestination = (DefaultListModel)list_destinationFiles.getModel();
        for (int indexDestination = 0; indexDestination < anArrayDestinationFiles.length; indexDestination++)
        {            
            listModelDestination.add(indexDestination, anArrayDestinationFiles[indexDestination]);
            lbl_listCount_destination.setText(String.valueOf(listModelDestination.getSize()));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_destinationFiles = new javax.swing.JList<>();
        btn_openSourceFolder = new javax.swing.JButton();
        btn_openDestinationFolder = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_sourceFiles = new javax.swing.JList<>();
        btn_close = new javax.swing.JButton();
        btn_convertToPDF = new javax.swing.JButton();
        lbl_listCount_source = new javax.swing.JLabel();
        lbl_listCount_destination = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(20, 20, 0, 0));

        jScrollPane2.setViewportView(list_destinationFiles);

        btn_openSourceFolder.setText("Quellordner öffnen");
        btn_openSourceFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openSourceFolderActionPerformed(evt);
            }
        });

        btn_openDestinationFolder.setText("Zielordner öffnen");

        jToolBar1.setRollover(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        list_sourceFiles.setToolTipText("");
        list_sourceFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_sourceFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_sourceFiles);

        btn_close.setText("Schließen");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_convertToPDF.setText("Ausgewählte Datei konvertieren");
        btn_convertToPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertToPDFActionPerformed(evt);
            }
        });

        lbl_listCount_source.setText("123");

        lbl_listCount_destination.setText("123");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_listCount_destination)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_listCount_source)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_close))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_convertToPDF)
                                .addGap(27, 27, 27)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_openDestinationFolder)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(746, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_openSourceFolder)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1439, 1439, 1439))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1651, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_convertToPDF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_openDestinationFolder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_listCount_source)
                    .addComponent(lbl_listCount_destination))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_close))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btn_openSourceFolder)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(628, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_openSourceFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openSourceFolderActionPerformed
        // TODO add your handling code here:
         // JFileChooser-Objekt erstellen
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter("Excel-Dateien","xls","xlsx");
        fileChooser.addChoosableFileFilter(filefilter);
        
        // Dialog zum Oeffnen von Dateien anzeigen
        int resultOfDialog = fileChooser.showDialog(null,"Excel-Dateien öffnen");
        if(resultOfDialog == JFileChooser.APPROVE_OPTION) {    
            
        //            
        }

    }//GEN-LAST:event_btn_openSourceFolderActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_convertToPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertToPDFActionPerformed
        // TODO add your handling code here:
        InputStream input = null;
        try 
        {
        String myExcelPath = "U:\\Ablage\\kunst_mi\\excel\\materialwirtschaft - produktion\\arbeitsvorbereitung\\1stammdaten\\";        
        input = new FileInputStream(myExcelPath + list_sourceFiles.getSelectedValue());
        Workbook wb = new SSWorkbook();
//        HSSFWorkbook wb = new HSSFWorkbook(input);
//        HSSFSheet sheet = wb.getSheet("EON VPP Nomination");
        for (int sheetIndex = 1; sheetIndex <= wb.getNumberOfSheets(); sheetIndex++)
        {
            if (!wb.getSheetName(sheetIndex).startsWith("vp"))
            {
                wb.removeSheetAt(sheetIndex);
            }
        }
        
        for (int sheetIndex = 1; sheetIndex <= wb.getNumberOfSheets(); sheetIndex++)
        {
            if (!wb.getSheetName(sheetIndex).startsWith("vp"))
            {
                wb.removeSheetAt(sheetIndex);
            }
        }        
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(ConverterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex) 
        {
            Logger.getLogger(ConverterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }  
        finally 
        {
            try {
                input.close();
            } catch (IOException ex) {
                Logger.getLogger(ConverterFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btn_convertToPDFActionPerformed

    private void list_sourceFilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_sourceFilesValueChanged
        // TODO add your handling code here:        
        DefaultListModel listModel = (DefaultListModel)list_sourceFiles.getModel();
        lbl_listCount_source.setText(String.valueOf(listModel.getSize()));
    }//GEN-LAST:event_list_sourceFilesValueChanged

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            String [] temp = new String [1];
            String [] tempTwo = new String [1];
            temp [0] = "eins";
            tempTwo [0] = "zwei";
            new ConverterFrame(temp, tempTwo).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_convertToPDF;
    private javax.swing.JButton btn_openDestinationFolder;
    private javax.swing.JButton btn_openSourceFolder;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_listCount_destination;
    private javax.swing.JLabel lbl_listCount_source;
    private javax.swing.JList<String> list_destinationFiles;
    private javax.swing.JList<String> list_sourceFiles;
    // End of variables declaration//GEN-END:variables
   
 }
